const $=id=>document.getElementById(id);const cats=window.CATS;let current=null,bags={short:[],dense:[],plain:[]},busy=false,saved=new Set(),last=null;
try{const value=JSON.parse(localStorage.getItem('daily-cat-saved')||'[]');if(Array.isArray(value))saved=new Set(value.filter(id=>cats.some(c=>c.id===id)));last=localStorage.getItem('daily-cat-last');}catch{}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,1800);}
function persist(){try{localStorage.setItem('daily-cat-saved',JSON.stringify([...saved]));localStorage.setItem('daily-cat-last',current?.id||'');}catch{toast('저장 실패');}}
function refreshHeart(){const yes=saved.has(current?.id);$('save-photo').textContent=yes?'♥':'♡';$('save-photo').classList.toggle('saved',yes);$('save-photo').setAttribute('aria-pressed',String(yes));$('save-photo').setAttribute('aria-label',yes?'고양이 저장 취소':'고양이 저장');}
function show(cat){current=cat;$('photo-error').hidden=true;$('cat-photo').src=cat.local;$('cat-photo').alt=cat.alt;$('source').href=cat.source;$('google').href='https://www.google.com/search?tbm=isch&q='+encodeURIComponent(cat.name+' cat meme');$('pinterest').href='https://www.pinterest.com/search/pins/?q='+encodeURIComponent(cat.name+' funny cat');refreshHeart();persist();}
function next(){if(busy)return;const pool=CatRandom.choosePool(cats);const key=pool[0]?.hasText?(pool[0].textDensity==='dense'?'dense':'short'):'plain';if(!bags[key].length)bags[key]=CatRandom.makeBag(pool.map(c=>c.id),current?.id||last);const id=bags[key].pop();show(cats.find(c=>c.id===id));busy=true;$('next').disabled=true;setTimeout(()=>{busy=false;$('next').disabled=false;},180);}
$('next').onclick=next;$('cat-photo').onerror=()=>$('photo-error').hidden=false;
$('save-photo').onclick=()=>{if(saved.has(current.id))saved.delete(current.id);else saved.add(current.id);refreshHeart();persist();};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!$('modal').open&&!['BUTTON','A','INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();next();}});
$('saved-open').onclick=()=>{$('modal-body').replaceChildren();const selected=cats.filter(c=>saved.has(c.id));if(!selected.length){const p=document.createElement('p');p.className='empty';p.textContent='저장한 사진 없음';$('modal-body').append(p);}else{const grid=document.createElement('div');grid.className='saved-grid';for(const cat of selected){const button=document.createElement('button');const image=document.createElement('img');image.src=cat.local;image.alt=cat.alt;button.append(image);button.onclick=()=>{show(cat);bags={short:[],dense:[],plain:[]};$('modal').close();};grid.append(button);}$('modal-body').append(grid);}$('modal').showModal();};
$('modal-close').onclick=()=>$('modal').close();$('modal').onclick=e=>{if(e.target!==$('modal'))return;const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('modal').close();};
next();
